version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: pet_nginx
    depends_on: 
      - pet-app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pet
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/cert:/cert
      - ./LOG_nginx:/var/log/nginx/
  
  mysql:
    image: mysql:8
    container_name: pet_mysql
    volumes:
      - ./DATA:/var/lib/mysql
    networks:
      - pet
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wms     
      MYSQL_USER: stefan
      MYSQL_PASSWORD: passwd

  pet-app:
    image: pet/app:latest
    container_name: pet-app
    depends_on: 
      - mysql
    restart: always
    volumes:
      - ./LOG_app:/var/log
    networks:
      - pet


networks:
    pet:
      driver: bridge
